dhcom: add quad and duallite defconfig

diff --git a/uboot_make b/uboot_make
--- a/uboot_make
+++ b/uboot_make
@@ -1,6 +1,14 @@
 echo ============================
 echo -- run u-boot i.mx6 build 
 echo ----------------------------
+
+if [ "$#" == "0" ]; then
+    echo "Error: No arguments provided"
+    echo "q = Quad core"
+    echo "dl = DualLite core"
+    exit 1
+fi
+
 echo -- setup toolchain 
 PATH=$PATH:/opt/eldk-5.4/armv7a/sysroots/i686-eldk-linux/usr/bin:/opt/eldk-5.4/armv7a/sysroots/i686-eldk-linux/usr/bin/armv7a-vfp-neon-linux-gnueabi
 export PATH
@@ -8,16 +16,25 @@ CROSS_COMPILE=armv7a-
 export CROSS_COMPILE
 
 echo ----------------------------
-echo --> make distclean
+echo -- make distclean
 make distclean
 
 echo ----------------------------
-echo --> delete old u-boot* files
+echo -- delete old u-boot* files
 rm -v u-boot*
 
 echo ----------------------------
-make dh_imx6dl_config
-#make mx6qsabresd_config
+if [ "$1" = "q" ] 
+then
+    echo "QUAD core selected"
+    make dh_imx6q_config
+elif [ "$1" = "dl" ] 
+then
+    echo "DualLite core selected"
+    make dh_imx6dl_config
+else
+    echo "Wrong argument"
+fi
 
 echo -- make u-boot imx6 
 make all > u-boot.txt
